/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodoRouteImport } from './routes/todo'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiProfileAvatarRouteImport } from './routes/api/profile/avatar'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTodosTodoIdImageRouteImport } from './routes/api/todos/$todoId/image'

const TodoRoute = TodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileAvatarRoute = ApiProfileAvatarRouteImport.update({
  id: '/api/profile/avatar',
  path: '/api/profile/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosTodoIdImageRoute = ApiTodosTodoIdImageRouteImport.update({
  id: '/api/todos/$todoId/image',
  path: '/api/todos/$todoId/image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/todo': typeof TodoRoute
  '/api/health': typeof ApiHealthRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/profile/avatar': typeof ApiProfileAvatarRoute
  '/api/todos/$todoId/image': typeof ApiTodosTodoIdImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/todo': typeof TodoRoute
  '/api/health': typeof ApiHealthRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/profile/avatar': typeof ApiProfileAvatarRoute
  '/api/todos/$todoId/image': typeof ApiTodosTodoIdImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/todo': typeof TodoRoute
  '/api/health': typeof ApiHealthRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/profile/avatar': typeof ApiProfileAvatarRoute
  '/api/todos/$todoId/image': typeof ApiTodosTodoIdImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/todo'
    | '/api/health'
    | '/profile/edit'
    | '/profile/'
    | '/api/auth/$'
    | '/api/profile/avatar'
    | '/api/todos/$todoId/image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/todo'
    | '/api/health'
    | '/profile/edit'
    | '/profile'
    | '/api/auth/$'
    | '/api/profile/avatar'
    | '/api/todos/$todoId/image'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/todo'
    | '/api/health'
    | '/profile/edit'
    | '/profile/'
    | '/api/auth/$'
    | '/api/profile/avatar'
    | '/api/todos/$todoId/image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TodoRoute: typeof TodoRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiProfileAvatarRoute: typeof ApiProfileAvatarRoute
  ApiTodosTodoIdImageRoute: typeof ApiTodosTodoIdImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/avatar': {
      id: '/api/profile/avatar'
      path: '/api/profile/avatar'
      fullPath: '/api/profile/avatar'
      preLoaderRoute: typeof ApiProfileAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todos/$todoId/image': {
      id: '/api/todos/$todoId/image'
      path: '/api/todos/$todoId/image'
      fullPath: '/api/todos/$todoId/image'
      preLoaderRoute: typeof ApiTodosTodoIdImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TodoRoute: TodoRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiProfileAvatarRoute: ApiProfileAvatarRoute,
  ApiTodosTodoIdImageRoute: ApiTodosTodoIdImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
